version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: loryblu
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - loryblu_data:/var/lib/mysql

volumes:
  loryblu_data: